### ISSUE TITLE
Unable to connect Google account after fresh install

### ISSUE THREAD

**Issue by artistechnic** [ubports/ubuntu-system-settings-online-accounts#4]
After a fresh install, I am unable to connect to my Google account through the Accounts panel:

Device: Hammerhead
OS Version: 16.04 Stable

_Device behavior:_
1. Click **Add Account...**
2. Click **Google**
3. Enter email and click **Next**
4. Enter Password and click **Next**
5. Enter 2-factor authentication and click **Done**
6. Click **Allow** to authorize presented option of 'offline access'
7. Advances to **_Loading..._** screen for Google and hangs with spinner gadget spinning endlessly. Only option is to quit with **Cancel** button.

_Expected behavior:_

After clicking **Allow** in step 6 above, device should complete authorization of Google account.

_Additional information:_
- This behavior is repeatable attempting to connect using the Contacts app.
- Connected successfully to GMail using Dekko2 0.1.6 Beta 1 with app-specific password (no OAuth)

**Comment by UniversalSuperBox** [comment]
I believe this issue has been fixed in a past update of Ubuntu Touch. However, at the moment we have another issue signing in to Google accounts via the online-accounts subsystem: https://github.com/ubports/account-plugins/issues/40.

Until this is fixed, it is very difficult for people to sign in to their Google accounts.

I will still close this report since I believe it's been fixed.
